# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-22 16:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import orders.models
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.IntegerField()),
                ('date', models.DateField(blank=True, help_text='If left blank, this will be the default limit for all days.', null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('create_date', models.DateTimeField(default=datetime.datetime.now)),
                ('last_updated', models.DateTimeField(default=datetime.datetime.now)),
                ('pickup_date', models.DateField()),
                ('quantity', models.IntegerField(validators=[orders.models.multiple_of_ten, orders.models.greater_than_zero])),
                ('requester_name', models.CharField(max_length=128)),
                ('requester_email', models.CharField(max_length=128)),
                ('requester_phone_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128)),
                ('comments', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('FILLED', 'Filled'), ('CANCELED', 'Canceled')], default='PENDING', max_length=128)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_pound', models.DecimalField(decimal_places=2, max_digits=8)),
                ('min_quantity', models.IntegerField()),
            ],
            options={
                'ordering': ['-min_quantity'],
            },
        ),
    ]
