# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-28 10:50
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='requester_email',
            field=models.CharField(max_length=128, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
