# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-05 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='requester_phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_date',
            field=models.DateTimeField(),
        ),
    ]
