# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20170305_1905'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_pound', models.DecimalField(decimal_places=2, max_digits=8)),
                ('min_quantity', models.IntegerField()),
            ],
            options={
                'ordering': ['-min_quantity'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
            preserve_default=False,
        ),
    ]
