# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-14 22:26
from __future__ import unicode_literals

import uuid

from django.db import migrations


def delete_old_orders(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Order = apps.get_model("orders", "Order")
    Order.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20170314_1523'),
    ]

    operations = [
        migrations.RunPython(delete_old_orders),
    ]


