# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_delete_all_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FILLED', 'Filled'), ('CANCELED', 'Canceled')], default='PENDING', max_length=128),
        ),
    ]
