# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-16 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20170316_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.IntegerField()),
                ('date', models.DateField(null=True, unique=True)),
            ],
        ),
    ]
